Switch from [ (aka test) to grep -q

diff --git a/.github/workflows/check_pr_title.yml b/.github/workflows/check_pr_title.yml
--- a/.github/workflows/check_pr_title.yml
+++ b/.github/workflows/check_pr_title.yml
@@ -16,10 +16,10 @@ jobs:
           
           jira_regex="ADFA-[0-9]+"
           echo "<$jira_regex> <$PR_TITLE>"
-
-          if [[ "$PR_TITLE" =~ "$jira_regex" ]]; then
-            echo "PR title '$PR_TITLE' contains a valid JIRA issue key."
+          
+          if grep -q "$jira_regex" <<< "$PR_TITLE"; then
+            echo "PR title `$PR_TITLE` contains a valid JIRA issue key."
           else
-            echo "Error: PR title '$PR_TITLE' does not contain a valid JIRA issue key. Please ensure your title includes a key in the format ADFA-XXXX."
-            exit 1
+              echo "Error: PR title `$PR_TITLE` does not contain a valid JIRA issue key. Please ensure your title includes a key in the format ADFA-XXXX."
+              exit 1
           fi
